Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,7 +50,12 @@ jobs:
       run: dotnet-coverage collect "dotnet test --no-build --configuration Release" -f xml -o "coverage.xml"
 
     - name: Verify coverage file
-      run: ls -l coverage.xml
+      run: |
+        if [ ! -f "coverage.xml" ]; then
+          echo "Coverage file not found!"
+          exit 1
+        fi
+        cat coverage.xml
 
     - name: SonarCloud End Analysis
       run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
